
services:
  db:
    image: postgres
    container_name: postgres-drivenops_test
    restart: always
    ports:
      - 1234:5432
    env_file:
      - back-end/.env.test

  node_app:
    container_name: node_app_test
    build: ./back-end
    ports:
      - 4000:4000
    depends_on:
      - db
    env_file:
      - back-end/.env.test
