
services:
  db:
    image: postgres
    container_name: postgres-drivenops
    restart: always
    ports:
      - 1234:5432
    env_file:
      - .env.test

  node_app:
    container_name: node_app
    build: ./back-end
    ports:
      - 4000:4000
    depends_on:
      - db
    env_file:
      - .env.test

  react_students_app: